//movie actions
export const REQUEST_MOVIES_START = "REQUEST_MOVIES_START";
export const REQUEST_MOVIES_SUCCESS = "REQUEST_MOVIES_SUCCESS";
export const REQUEST_MOVIES_FAILURE = "REQUEST_MOVIES_FAILURE";

//sort actions
export const REQUEST_SORT_ORDER_OPTIONS_START = "REQUEST_SORT_ORDER_OPTIONS_START";
export const REQUEST_SORT_ORDER_OPTIONS_SUCCESS = "REQUEST_SORT_ORDER_OPTIONS_SUCCESS";
export const REQUEST_SORT_ORDER_OPTIONS_FAILURE = "REQUEST_SORT_ORDER_OPTIONS_FAILURE";
export const SORT_BY_RELEASE_DATE = "SORT_BY_RELEASE_DATE";
export const SORT_BY_RANK = "SORT_BY_RANK";
export const SORT_MOVIES = "SORT_MOVIES";
